### ISSUE TITLE
Not compatible with themes?

### ISSUE THREAD

**Issue by ghost** [Vap0r1ze/audioviz#13]
I am using the MaterialDiscord theme, does this plugin suport themes as it used to work for me on MaterialDiscord up until recent Powercord update.

**Comment by Vap0r1ze** [comment]
I don't know what you're asking

**Comment by ghost** [comment]
I asked whether your plugin would work when using powercord skins, not sure what i typed wrong there but oh well. From further testing, it does not work at all on powercord with skins.

**Comment by Vap0r1ze** [comment]
I don't think the plugin works in general for most people currently. I suspect it has something to do with the fact that Discord is using electron@9.3.5 because I've seen many Electron issues with MediaDevices where the closing response is along the lines of "fixed in v10"

**Comment by Vap0r1ze** [comment]
Going to close because this question is unanswerable until the basic functions of the plugin can be consistently reproduced
