### ISSUE TITLE
Discord not starting after Installation

### ISSUE THREAD

**Issue by SCDerox** [Vap0r1ze/audioviz#2]
I installed the plugin and now the discord client crashes every time I start it. After I removed the plugin folder everything worked fine again. 
Version-Data:

Canary 62780 (bd33cff)
Host 0.0.266
Windows 10 64-Bit (10.0.19041)
Powercord v2 (f8180d3)

**Comment by rcnsh** [comment]
Im getting the same issue
[discord-2021-01-08_12-29-57.txt](https://github.com/Vap0r1ze/audioviz/files/5787173/discord-2021-01-08_12-29-57.txt)

**Comment by Vap0r1ze** [comment]
@RCNOverwatcher I probably know the issue you're having, but the error that you're dealing with isn't in that text file.

**Comment by rcnsh** [comment]
Is there any sort of workaround currently or is it just an issue that will be fixed with time?

**Comment by Vap0r1ze** [comment]
I believe Electron v8 and v9 have a lot of bugs related to the interfacing of media devices, and I've seen many Electron issues that end with "fixed in v10". Since Discord (as of right now) uses electron@9.3.5, I think the only fix is to wait for Discord to update their version of Electron.

**Comment by Vap0r1ze** [comment]
Is this issue resolved now that discord is on electron v13?

**Comment by SCDerox** [comment]
Can't test it, as I am not longer using powercord and I am not longer on windows. I have closed this because this project seemed kinda inactive and this issue always popped up in my GitHub feed, but if it is still relevant I am happy to reopen it anytime ^^
