### ISSUE TITLE
Sound display shows up, but only for microphone audio

### ISSUE THREAD

**Issue by Titaniumtown** [Vap0r1ze/audioviz#5]
So this plugin just started working again (it didn't display in the past), but with one big issue, the audio visualization isn't of spotify, but of my microphone. Just for context, I'm on linux.

**Comment by Titaniumtown** [comment]
now after #4 was reverted in #6 no audio is visualized at all.

**Comment by Vap0r1ze** [comment]
#4 offered a fix and after quickly testing it seemed to work, but it was reverted shortly after due to it only recording microphone audio rather than desktop audio

**Comment by Titaniumtown** [comment]
but now no audio is displayed at all.
